version: 2
updates:
  - package-ecosystem: gomod
    directories: ["/", "/tools/*"]
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directories: ["/", "/sandbox"]
    schedule:
      interval: weekly
